name: restfulplus
version: 0.1.2
authors:
- Dan Schultz <dan@mixbook.com>
- Anton Astashov <anton@mixbook.com>
- modified by Marek Kaszewski
description: A package for working with restful web services with cache.
homepage: http://www.github.com/MarkoVcode/restful.dart
dependencies:
  logging: '>=0.5.13'
  mock: any
dev_dependencies:
  browser: any
  js: any
  logging_handlers: '>=0.5.0'
  unittest: any
